name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # This ensures the job's status is reported back to GitHub
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run model architecture tests
      id: architecture-test
      run: |
        pytest test_model.py::test_model_architecture -v
    
    - name: Run model training tests
      id: training-test
      run: |
        pytest test_model.py::test_model_training -v 